### ISSUE TITLE
2. Create the backend solution

### ISSUE THREAD

**Issue by michalusio** [michalusio/KuneKune#1]
We want to create a Visual Studio solution in the Backend folder.

Specifically, the structure should look like:
> Backend
>> Backend.sln
>> ...other files

To do so, first create and checkout a new branch (you can call it something like "backend-setup" or however you like).
Then, you want to open Visual Studio, select "Create a new project", and go through the whole process.
You should select:
- "ASP.NET Core Web API" as the type of the project
- the Backend folder as the root of the solution
- .NET 8.0 as the framework
- No authentication
- No HTTPS support
- Enable Docker (Linux as the OS)
- Enable OpenAPI support
- Top-level statements doesn't matter, we can go either
- Use controllers

After creating the solution, do not forget to commit the changes and create a PR to the master branch.

**Comment by Gyllenberg** [comment]
I committed a new branch as I didn't read the issue correctly.
