### ISSUE TITLE
1. Download the repository

### ISSUE THREAD

**Issue by michalusio** [michalusio/KuneKune#2]
1. Install Git. It's the tool for managing code we create. It allows us to synchronize our changes with others, and make pull requests, so others can review our code before merging it into the main codebase
2. Go to a folder where you have your projects and download this repository. Downloading can be done using a GUI of some kind, or you can just use the command line:
`git clone https://github.com/michalusio/KuneKune`

**Comment by Gyllenberg** [comment]
Should be completed.
