### ISSUE TITLE
4. Create a banner and a header

### ISSUE THREAD

**Issue by majarzabek** [michalusio/KuneKune#5]
We should have at least 2 components there:
1. header
2. banner 

Please use modular styles and keep in mind, that some elements will be reused (eg. button), so you can choose to either create a component for the button, or use globally available styles for it (the first option is better). The picture will be stored in assets, on React side.

Please use scss for styling, as it is much more convenient to use than plain css.
To enable it, install the sass package using `npm install -D sass`.
To create a modular style, the extension should be `.module.scss`.
Then you can import the style in the component by writing `import styles from <filepath>;`

![image](https://github.com/michalusio/KuneKune/assets/48184243/6774efc6-5919-448b-a3b3-a1df3a4b0ab4)

**Comment by Gyllenberg** [comment]
I would argue this task has been completed thanks to magda?
