### ISSUE TITLE
Download Docker

### ISSUE THREAD

**Issue by michalusio** [michalusio/KuneKune#7]
> [!NOTE]
> A "container" is akin to a virtual machine - programs running inside a container cannot affect things outside the container (if you don't allow them to). They think they are running on a different machine entirely.
It is a very convenient concept, as it allows us to e.g. run 10 different databases, backend and frontends without having to install any dependencies of them on your computer - you just download the "image", e.g. a snapshot of a container, and run it.

Docker is a tool for managing such containers.
You can download Docker Desktop (which is the GUI) [here](https://www.docker.com/products/docker-desktop/)
> [!WARNING]
> If you're using a laptop from Columbus, be wary that your support will catch you and you will have to explain yourself, as using Docker Desktop for commercial use requires a paid license. If that's the case, you could use the command line after installing just the Docker Engine.

Overall, we will be using Docker to run the database locally, so we can store e.g. articles and other stuff in it, and serve it from the backend to the frontend.

**Comment by Gyllenberg** [comment]
I do have docker installed. 

![Dock ](https://github.com/michalusio/KuneKune/assets/136751776/f3fea40f-f94e-472d-b0ad-ead2cef35420)
