### ISSUE TITLE
Set a nice font for the project

### ISSUE THREAD

**Issue by michalusio** [michalusio/KuneKune#9]
We want our website to look nice, so we have to add a nice font to it.
The usual choice is something like [Lato](https://fonts.google.com/specimen/Lato), although you can select a different font if something catches your eye.

As said on the Google page, you need to add a few HTML tags to the <head> tag, which is located in `Frontend/index.html`

An explanation of the tags:
- `<link rel="preconnect" href=X>` - this tag tells the browser to immediately create a connection to the given url. It increases the download performance, as when the browser gets down to parsing the line containing a file download, the connection is already established.
- `<link rel="stylesheet" href=X>` - this tag tells the browser that it should load a file specified by a given url, and treat it as a stylesheet (i.e. a CSS file). That is the primary way of loading style files for your site.

> [!WARNING]
> Make sure that the branch you create is created from up-to-date master.

> [!NOTE]
> To update a branch, first checkout it, then do `git pull`

**Comment by Gyllenberg** [comment]
AddedFontsPR
